[package]
name = "webpki-roots"
version = "1.0.6"
edition = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
license = "CDLA-Permissive-2.0"
homepage = { workspace = true }
repository = { workspace = true }
description = "Mozilla's CA root certificates for use with webpki"

[dependencies]
pki-types = { workspace = true }

[dev-dependencies]
aws-lc-rs = { workspace = true }
hex = { workspace = true }
percent-encoding = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
webpki = { workspace = true }
webpki-ccadb = { path = "../webpki-ccadb" }
x509-parser = { workspace = true }
yasna = { workspace = true }
